<?php

namespace Machour\DataTable\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Machour\DataTable\Columns\Column;
use Machour\DataTable\DataTableMeta;
use Machour\DataTable\DataTableResponse;
use Machour\DataTable\QuickView;
use ReflectionClass;
use ReflectionNamedType;

class GenerateTypeScript extends Command
{
    protected $signature = 'data-table:types
        {--output=resources/js/types/data-table.d.ts : Output file path}';

    protected $description = 'Generate TypeScript type definitions from data table PHP classes';

    public function __construct(private Filesystem $files)
    {
        parent::__construct();
    }

    public function handle(): int
    {
        $output = base_path($this->option('output'));

        $types = $this->generateTypes();

        $this->files->ensureDirectoryExists(dirname($output));
        $this->files->put($output, $types);

        $this->components->info("TypeScript types generated: {$output}");

        return self::SUCCESS;
    }

    private function generateTypes(): string
    {
        $classes = [
            Column::class,
            DataTableResponse::class,
            DataTableMeta::class,
            QuickView::class,
        ];

        $lines = [
            '// Auto-generated by php artisan data-table:types',
            '// Do not edit manually',
            '',
            'declare namespace DataTable {',
        ];

        foreach ($classes as $class) {
            $lines[] = $this->classToInterface($class);
        }

        // Also scan app/DataTables for user-defined tables
        $dataTablesPath = app_path('DataTables');
        if ($this->files->isDirectory($dataTablesPath)) {
            $files = $this->files->glob($dataTablesPath . '/*.php');
            foreach ($files as $file) {
                $className = 'App\\DataTables\\' . pathinfo($file, PATHINFO_FILENAME);
                if (class_exists($className)) {
                    $lines[] = $this->dataTableToInterface($className);
                }
            }
        }

        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function classToInterface(string $class): string
    {
        $reflection = new ReflectionClass($class);
        $shortName = $reflection->getShortName();
        $lines = ["    export interface {$shortName} {"];

        $constructor = $reflection->getConstructor();
        if ($constructor) {
            foreach ($constructor->getParameters() as $param) {
                $tsType = $this->phpTypeToTs($param->getType());
                $optional = $param->isOptional() || ($param->getType() instanceof ReflectionNamedType && $param->getType()->allowsNull()) ? '?' : '';
                $lines[] = "        {$param->getName()}{$optional}: {$tsType};";
            }
        }

        $lines[] = '    }';
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function dataTableToInterface(string $class): string
    {
        $reflection = new ReflectionClass($class);
        $shortName = $reflection->getShortName();
        $lines = ["    export interface {$shortName} {"];

        $constructor = $reflection->getConstructor();
        if ($constructor) {
            foreach ($constructor->getParameters() as $param) {
                if ($param->isPromoted()) {
                    $tsType = $this->phpTypeToTs($param->getType());
                    $optional = ($param->getType() instanceof ReflectionNamedType && $param->getType()->allowsNull()) ? '?' : '';
                    $lines[] = "        {$param->getName()}{$optional}: {$tsType};";
                }
            }
        }

        $lines[] = '    }';
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function phpTypeToTs(?\ReflectionType $type): string
    {
        if ($type === null) {
            return 'unknown';
        }

        if ($type instanceof ReflectionNamedType) {
            $name = $type->getName();
            $tsType = match ($name) {
                'int', 'float' => 'number',
                'string' => 'string',
                'bool' => 'boolean',
                'array' => 'unknown[]',
                'null' => 'null',
                'mixed' => 'unknown',
                'Closure' => '((...args: unknown[]) => unknown)',
                default => 'unknown',
            };

            if ($type->allowsNull() && $name !== 'null') {
                return "{$tsType} | null";
            }

            return $tsType;
        }

        return 'unknown';
    }
}
