<?php

use Machour\DataTable\Concerns\HasAuditLog;
use Machour\DataTable\Console\Commands\GenerateTranslations;

// ── GenerateTranslations command ──────────────────────────

test('GenerateTranslations command class exists', function () {
    expect(class_exists(GenerateTranslations::class))->toBeTrue();
});

test('GenerateTranslations has correct signature', function () {
    $reflection = new ReflectionClass(GenerateTranslations::class);
    $prop = $reflection->getProperty('signature');
    $prop->setAccessible(true);

    $command = $reflection->newInstanceWithoutConstructor();
    $signature = $prop->getValue($command);

    expect($signature)->toContain('data-table:translations');
    expect($signature)->toContain('--lang');
    expect($signature)->toContain('--all');
    expect($signature)->toContain('--output');
});

test('GenerateTranslations has built-in language packs', function () {
    $reflection = new ReflectionClass(GenerateTranslations::class);
    $prop = $reflection->getProperty('translations');
    $prop->setAccessible(true);

    $command = $reflection->newInstanceWithoutConstructor();
    $translations = $prop->getValue($command);

    $expectedLangs = ['en', 'fr', 'es', 'de', 'pt', 'ar', 'zh', 'ja'];

    foreach ($expectedLangs as $lang) {
        expect($translations)->toHaveKey($lang);
    }
});

test('GenerateTranslations each language has required keys', function () {
    $reflection = new ReflectionClass(GenerateTranslations::class);
    $prop = $reflection->getProperty('translations');
    $prop->setAccessible(true);

    $command = $reflection->newInstanceWithoutConstructor();
    $translations = $prop->getValue($command);

    $requiredKeys = [
        'totalResults', 'rowsPerPage', 'pageOf', 'columns', 'filter', 'search',
        'yes', 'no', 'selectAll', 'cancel', 'save', 'noData', 'actions', 'loading',
        'density', 'undo', 'redo', 'keyboardShortcuts', 'close', 'emptyTitle',
    ];

    foreach ($translations as $lang => $strings) {
        foreach ($requiredKeys as $key) {
            expect(array_key_exists($key, $strings))->toBeTrue("Language '{$lang}' is missing key '{$key}'");
        }
    }
});

test('GenerateTranslations buildTypeScript generates valid content', function () {
    $reflection = new ReflectionClass(GenerateTranslations::class);
    $method = $reflection->getMethod('buildTypeScript');
    $method->setAccessible(true);

    $command = $reflection->newInstanceWithoutConstructor();
    $result = $method->invoke($command, 'es', [
        'columns' => 'Columnas',
        'filter' => 'Filtrar',
        'totalResults' => '(count) => `${count} resultado${count !== 1 ? "s" : ""}`',
    ]);

    expect($result)->toContain('esTranslations');
    expect($result)->toContain("'Columnas'");
    expect($result)->toContain("'Filtrar'");
    expect($result)->toContain('(count) =>');
    expect($result)->toContain('Generated by');
});

// ── HasAuditLog trait ──────────────────────────

test('HasAuditLog trait exists', function () {
    expect(trait_exists(HasAuditLog::class))->toBeTrue();
});

test('HasAuditLog trait has required methods', function () {
    $reflection = new ReflectionClass(HasAuditLog::class);
    $methods = array_map(fn ($m) => $m->getName(), $reflection->getMethods());

    expect($methods)->toContain('tableAuditLogName');
    expect($methods)->toContain('tableAuditLogTable');
    expect($methods)->toContain('tableAuditLogEnabled');
    expect($methods)->toContain('logInlineEdit');
    expect($methods)->toContain('logToggle');
    expect($methods)->toContain('logReorder');
    expect($methods)->toContain('logBulkAction');
    expect($methods)->toContain('getAuditLog');
    expect($methods)->toContain('getRowAuditLog');
});

test('HasAuditLog tableAuditLogName is abstract', function () {
    $reflection = new ReflectionClass(HasAuditLog::class);
    $method = $reflection->getMethod('tableAuditLogName');

    expect($method->isAbstract())->toBeTrue();
});

test('HasAuditLog default table name is data_table_audit_log', function () {
    $class = new class {
        use HasAuditLog;

        public static function tableAuditLogName(): string
        {
            return 'test-table';
        }
    };

    expect($class::tableAuditLogTable())->toBe('data_table_audit_log');
});

test('HasAuditLog default enabled is true', function () {
    $class = new class {
        use HasAuditLog;

        public static function tableAuditLogName(): string
        {
            return 'test-table';
        }
    };

    expect($class::tableAuditLogEnabled())->toBeTrue();
});

test('HasAuditLog enabled can be overridden to false', function () {
    $class = new class {
        use HasAuditLog;

        public static function tableAuditLogName(): string
        {
            return 'test-table';
        }

        public static function tableAuditLogEnabled(): bool
        {
            return false;
        }
    };

    expect($class::tableAuditLogEnabled())->toBeFalse();
});

// ── Audit log migration ──────────────────────────

test('audit log migration file exists', function () {
    $migrationPath = realpath(__DIR__ . '/../../database/migrations/create_data_table_audit_log_table.php');
    expect($migrationPath)->not->toBeFalse();
});

test('audit log migration returns Migration instance', function () {
    $migrationPath = realpath(__DIR__ . '/../../database/migrations/create_data_table_audit_log_table.php');
    $migration = require $migrationPath;

    expect($migration)->toBeInstanceOf(\Illuminate\Database\Migrations\Migration::class);
});

// ── DataTableServiceProvider registers new command ──────────────────────────

test('service provider registers GenerateTranslations command', function () {
    $providerPath = realpath(__DIR__ . '/../../src/DataTableServiceProvider.php');
    $content = file_get_contents($providerPath);

    expect($content)->toContain('GenerateTranslations::class');
    expect($content)->toContain('use Machour\DataTable\Console\Commands\GenerateTranslations');
});

// ── Frontend types have batch 2 options ──────────────────────────

test('TypeScript types include batch 2 options', function () {
    $typesPath = realpath(__DIR__ . '/../../react/src/data-table/types.ts');
    $content = file_get_contents($typesPath);

    expect($content)->toContain('undoRedo: boolean');
    expect($content)->toContain('columnPinning: boolean');
    expect($content)->toContain('persistSelection: boolean');
    expect($content)->toContain('shortcutsOverlay: boolean');
    expect($content)->toContain('exportProgress: boolean');
    expect($content)->toContain('emptyStateIllustration: boolean');
});

// ── Frontend i18n has batch 2 translation keys ──────────────────────────

test('i18n file includes batch 2 translation keys', function () {
    $i18nPath = realpath(__DIR__ . '/../../react/src/data-table/i18n.ts');
    $content = file_get_contents($i18nPath);

    // Undo/Redo
    expect($content)->toContain('undo: string');
    expect($content)->toContain('redo: string');
    expect($content)->toContain('editUndone: string');
    expect($content)->toContain('editRedone: string');

    // Column pinning
    expect($content)->toContain('pinColumn: string');

    // Keyboard shortcuts
    expect($content)->toContain('keyboardShortcuts: string');
    expect($content)->toContain('shortcutNavigation: string');

    // Export progress
    expect($content)->toContain('exporting: string');
    expect($content)->toContain('exportReady: string');
    expect($content)->toContain('exportDownload: string');

    // Empty state
    expect($content)->toContain('emptyTitle: string');
    expect($content)->toContain('emptyDescription: string');
});

test('i18n French translations include batch 2 keys', function () {
    $i18nPath = realpath(__DIR__ . '/../../react/src/data-table/i18n.ts');
    $content = file_get_contents($i18nPath);

    // French undo/redo
    expect($content)->toContain('Annuler');
    expect($content)->toContain('Refaire');
    expect($content)->toContain('Modification annulée');

    // French keyboard shortcuts
    expect($content)->toContain('Raccourcis clavier');

    // French export progress
    expect($content)->toContain('Export en cours...');
    expect($content)->toContain('Télécharger');

    // French empty state
    expect($content)->toContain('Aucune donnée');
});

// ── Frontend data-table.tsx has batch 2 components ──────────────────────────

test('data-table.tsx includes undo/redo hook', function () {
    $dtPath = realpath(__DIR__ . '/../../react/src/data-table/data-table.tsx');
    $content = file_get_contents($dtPath);

    expect($content)->toContain('function useUndoRedo');
    expect($content)->toContain('pushEdit');
    expect($content)->toContain('undoStack');
    expect($content)->toContain('redoStack');
});

test('data-table.tsx includes keyboard shortcuts dialog', function () {
    $dtPath = realpath(__DIR__ . '/../../react/src/data-table/data-table.tsx');
    $content = file_get_contents($dtPath);

    expect($content)->toContain('function KeyboardShortcutsDialog');
    expect($content)->toContain('shortcutNavigation');
    expect($content)->toContain('shortcutSelect');
});

test('data-table.tsx includes export with progress', function () {
    $dtPath = realpath(__DIR__ . '/../../react/src/data-table/data-table.tsx');
    $content = file_get_contents($dtPath);

    expect($content)->toContain('function ExportWithProgress');
    expect($content)->toContain('exporting');
    expect($content)->toContain('handleExport');
});

test('data-table.tsx includes empty state illustration', function () {
    $dtPath = realpath(__DIR__ . '/../../react/src/data-table/data-table.tsx');
    $content = file_get_contents($dtPath);

    expect($content)->toContain('function DefaultEmptyStateIllustration');
    expect($content)->toContain('function EmptyState');
    expect($content)->toContain('emptyTitle');
});

test('data-table.tsx includes selection persistence hook', function () {
    $dtPath = realpath(__DIR__ . '/../../react/src/data-table/data-table.tsx');
    $content = file_get_contents($dtPath);

    expect($content)->toContain('function usePersistedSelection');
    expect($content)->toContain('persistedIds');
    expect($content)->toContain('dt-selection-');
});

test('data-table.tsx includes column pin menu', function () {
    $dtPath = realpath(__DIR__ . '/../../react/src/data-table/data-table.tsx');
    $content = file_get_contents($dtPath);

    expect($content)->toContain('function ColumnPinMenu');
    expect($content)->toContain('handlePinColumn');
});

// ── Config file still valid ──────────────────────────

test('config file still has all expected keys after batch 2', function () {
    $configPath = realpath(__DIR__ . '/../../config/data-table.php');
    $config = require $configPath;

    expect($config)->toBeArray();
    expect($config)->toHaveKey('default_per_page');
    expect($config)->toHaveKey('max_per_page');
    expect($config)->toHaveKey('default_polling_interval');
    expect($config)->toHaveKey('storage_prefix');
    expect($config)->toHaveKey('middleware');
    expect($config)->toHaveKey('route_prefix');
    expect($config)->toHaveKey('export');
    expect($config)->toHaveKey('import');
});
